### ISSUE TITLE
Not able to run the project locally using Docker Container

### ISSUE THREAD

**Issue by VigneshVicky97** [mohamedsamara/mern-ecommerce#244]
**Describe the bug**
Not able to run project locally using Docker container.

**To Reproduce**
1. git clone https://github.com/mohamedsamara/mern-ecommerce.git
2. docker compose -f dockercompose.yml up
3. dockercompose.yml

```
version: '3'
services:
  client:
    build: client
    ports:
      - '8080:8080'
  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=my_token
      - MONGO_URI=mongodb://localhost:27017/my_database
      # - MONGO_URI=mongodb://mongo:27017/my_database
    ports:
      - '3000:3000'
```

**Obtained behavior**
```
client-1  |     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
client-1  | ℹ ｢wdm｣: Compiled successfully.                                                                                                                                     
server-1  | MongooseServerSelectionError: getaddrinfo ENOTFOUND mongo
server-1  |     at NativeConnection.Connection.openUri (/usr/src/app/node_modules/mongoose/lib/connection.js:823:32)
server-1  |     at Mongoose.connect (/usr/src/app/node_modules/mongoose/lib/index.js:333:15)                                                                                    
server-1  |     at setupDB (/usr/src/app/utils/db.js:13:8)                                                                                                                      
server-1  |     at Object.<anonymous> (/usr/src/app/index.js:25:1)
server-1  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)                                                                                                   
server-1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)                                                                                     
server-1  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
server-1  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)                                                                                              
server-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)                                                                           
server-1  |     at node:internal/main/run_main_module:22:47 {                                                                                                                   
server-1  |   reason: TopologyDescription {
server-1  |     type: 'Single',                                                                                                                                                 
server-1  |     setName: null,                                                                                                                                                  
server-1  |     maxSetVersion: null,                                                                                                                                            
server-1  |     maxElectionId: null,                                                                                                                                            
server-1  |     servers: Map(1) { 'mongo:27017' => [ServerDescription] },                                                                                                       
server-1  |     stale: false,                                                                                                                                                   
server-1  |     compatible: true,                                                                                                                                               
server-1  |     compatibilityError: null,                                                                                                                                       
server-1  |     logicalSessionTimeoutMinutes: null,
server-1  |     heartbeatFrequencyMS: 10000,                                                                                                                                    
server-1  |     localThresholdMS: 15,                                                                                                                                           
server-1  |     commonWireVersion: null                                                                                                                                         
server-1  |   }
server-1  | }    
```

**Desktop (please complete the following information):**
 - OS: Windows 11

I installed MongoDB and able to check using Mongosh.
How can I solve this error and run the program locally?

**Comment by mohamedsamara** [comment]
@VigneshVicky97 It should work with a remote MongoDB URI. However, if you want to connect to MongoDB locally, you must use your MongoDB service name in the docker which should be added to the `dockercompose.yml`.

**Comment by VigneshVicky97** [comment]
```
version: '3'

services:
  client:
    build: client
    ports:
      - '8080:8080'

  server:
    build: server
    environment:
      - PORT=3000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:8080
      - JWT_SECRET=my_token
      - MONGO_URI=mongodb://mongo:27017/my_database
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
```

I updated the docker-compose.yml file as the above one. Even after I won't get any output on local server. What will be the problem ? Are you able to run that locally ?

My output looks like:

![Screenshot 2024-08-29 102626](https://github.com/user-attachments/assets/1b4f601b-cf48-42cc-b739-08a8c97af50c)
